config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#index'
  resources :users,  only: :index
  resources :orders, only: [:index, :new, :create]
  resources :homes,  only: :index do
    collection do
      get 'tushima'
      get 'iki'
      get 'access'
    end
  end
  resources :foods,  only: [:new, :create, :edit, :update, :destroy, :index] do
    collection do
      get 'search'
    end
  end
  resources :hotels, only: [:new, :create, :edit, :update, :destroy, :index] do
    collection do
      get 'search'
    end
  end
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
      <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class='footer'>
  <div class='footer-contents'>
    <div class='furima-details'>
      <h2 class='footer-content-head'>壱岐市について</h2>
      <ul>
        <li><%= link_to '壱岐市公式HP', "https://www.city.iki.nagasaki.jp/", class: "footer-link" %></li>
        <li><%= link_to '壱岐市観光局', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>対馬市について</h2>
      <ul>
        <li><%= link_to '対馬市公式HP', "https://www.city.tsushima.nagasaki.jp/", class: "footer-link" %></li>
        <li><%= link_to '対馬市観光局', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>離島の友</h2>
      <ul>
        <li><%= link_to '日本離島センター', "https://www.nijinet.or.jp/", class: "footer-link" %></li>
        <li><%= link_to '離島の定義', "https://www.pref.kagoshima.jp/ac07/pr/shima/seika/documents/ritou-seika1-1.pdf", class: "footer-link" %></li>
        <li><%= link_to 'お知らせ', "#", class: "footer-link" %></li>
      </ul>
    </div>
  </div>
  <div class="footer-contents-lower">
    <%= link_to image_tag("tu_footer.png", class:"logo-white"), "https://www.city.iki.nagasaki.jp/" %>
    <%= link_to image_tag("heritage.png", class:"logo-white"), "https://japan-heritage.bunka.go.jp/ja/index.html" %>
    <%= link_to image_tag("iki-logo.png", class:"logo-white"), "https://www.city.tsushima.nagasaki.jp/" %>
  </div>
    <% unless user_signed_in? %>
      <a><%= link_to "管理者はこちら", new_user_session_path, class:"login" %></a>
    <% end %>
</div>

app/views/shared/_header.html.erb
<header class='top-page-header'>
  <div class='nav'>
    <div class='lists-left'>
      <div><%= link_to image_tag("islands.png",class:'islands-icon'), "/"  %>
      </div>
      <div class='language-select'>
        <div class='english-list'><%= link_to 'English', "#" %></div>
        <div class='korea-list'><%= link_to 'Korean', "#" %></div>
        <div class='china-list'><%= link_to 'Chinese', "#" %></div> 
      </div>
    </div>

    <ul class="lists-right">
      <li class="current"></li>
      <li><%= link_to "食べる", foods_path %></li>
      <li><%= link_to "泊まる", hotels_path %></li>
      <li><%= link_to "対馬を知る", tushima_homes_path %></li>
      <li><%= link_to "壱岐を知る", iki_homes_path %></li>
      <li><%= link_to "アクセス", access_homes_path %></li>
      <li><%= link_to "ふるさと納税", orders_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to current_user.nickname, users_path, class: "when-login" %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "when-login" %></li>
      <% end %>
    </ul>
  </nav>
</header>