config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#index'
  resources :users,  only: :index
  resources :orders, only: [:index, :new, :create]
  resources :homes,  only: :index do
    collection do
      get 'tushima'
      get 'iki'
      get 'access'
    end
  end
  resources :foods,  only: [:new, :create, :edit, :update, :destroy, :index] do
    collection do
      get 'search'
    end
  end
  resources :hotels, only: [:new, :create, :edit, :update, :destroy, :index] do
    collection do
      get 'search'
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  attr_accessor :token

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :item
  belongs_to :prefecture

  with_options presence: true do
    validates :first_name, :last_name, :first_name_kana, :last_name_kana
  end
  with_options allow_blank: true do
    with_options format: { with: /\A[ぁ-んァ-ン一-龥々ー]+\z/ } do
      validates :first_name, :last_name
    end
    with_options format: { with: /\A[ァ-ヶー－]+\z/ } do
      validates :first_name_kana, :last_name_kana
    end
  end
  with_options presence: true do
    validates :token, :postal_code, :city_word, :house_number, :phone_number
  end
  with_options allow_blank: true do
    validates :postal_code, format: { with: /\A[0-9]{3}-[0-9]{4}\z/, message: 'は不正な値です。ハイフン(-)を入れてください' }
    validates :phone_number, format: { with: /\A\d{10,11}+$\z/ }
  end
  with_options numericality: { other_than: 1, message: 'を選択してください' } do
    validates :prefecture_id, :item_id
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @items = Item.where.not(id: 1)
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    if @order.valid?
      pay_item
      @order.save
    else
      render :new
    end
  end

  private

  def order_params
    params.require(:order).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :item_id, :postal_code,
                                  :prefecture_id, :city_word, :house_number, :building_name, :phone_number).merge(token: params[:token])
  end

  def pay_item
    Payjp.api_key = ENV['PAYJP_SECRET_KEY']
    Payjp::Charge.create(
      amount: @order.item.price,
      card: order_params[:token],
      currency: 'jpy'
    )
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/create.html.erb
<div class="success-back">
  <div class="success">
    <h3>購入が完了しました。</h3>
    <a class="btn" href="/">トップページへ戻る</a>
  </div>
</div>

app/views/orders/index.html.erb
<div class="vcontents-row">
  <div class="furusato-contents">
    <div class="hotel-title">ふるさと納税一覧</div>
  </div>
  <ul class="hotel-data">
    <% @items.each do |item| %>
      <li class='lists'>
        <div class="photo-grid-order">
          <p><%= image_tag item.image , class: "img" %><p>
          <ul>
            <li><strong class="strong">エリア:</strong><%=item.island%></li>
            <li><strong class="strong">価格:￥</strong><%=item.price%></li>
          </ul>
        </div>
        <div class="info-grid_order">
          <ul class="info-field">
            <li><strong class="strong">商品名:</strong><%=item.name%></li>
            <li><strong class="strong">詳細:</strong><%=item.tagline%></li>
          </ul>
        </div>
      </li>
    <% end %>
  </ul>
  <div class="formm">
    <%= link_to  new_order_path do %>
    <div class="form-purches">購入フォームはこちら</div>
    <% end %>
  </div>
</div>

app/views/orders/new.html.erb
<div class='transaction-contents'>
  <div class='transaction-main'>
    <h1 class='info-input-haedline'>購入商品の選択</h1>
    <%= render 'shared/error_messages', model: @order %>
  <%= form_with model: @order, url: orders_path, id: 'charge-form', class: 'transaction-form-wrap',local: true do |f| %>
    <div class='buy-item-info'>
      <label class="form-text">返礼品</label>
      <span class="indispensable">必須</span>
      <%= f.collection_select(:item_id, Item.all, :id, :name, {}, {class:"select-box", id:"item"}) %>
    </div>

     <%# お客様情報入力 %>
    <div class='shipping-address-form'>
      <h1 class='info-input-haedline'>お客様情報の入力</h1>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">お名前(全角)</label>
          <span class="indispensable">必須</span>
        </div>
        <div class='input-name-wrap'>
          <%= f.text_area :last_name, class:"input-name", id:"last-name", placeholder:"例) 山田" %>
          <%= f.text_area :first_name, class:"input-name", id:"first-name", placeholder:"例) 陸太郎" %>
        </div>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">お名前カナ(全角)</label>
          <span class="indispensable">必須</span>
        </div>
        <div class='input-name-wrap'>
          <%= f.text_area :last_name_kana, class:"input-name", id:"last-name-kana", placeholder:"例) ヤマダ" %>
          <%= f.text_area :first_name_kana, class:"input-name", id:"first-name-kana", placeholder:"例) リクタロウ" %>
        </div>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">郵便番号</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :postal_code, class:"input-default", id:"postal-code", placeholder:"例）123-4567", maxlength:"8" %>
      </div>
      
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">都道府県</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"prefecture"}) %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">市区町村</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :city_word, class:"input-default", id:"city", placeholder:"例）横浜市緑区"%>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">番地</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :house_number, class:"input-default", id:"addresses", placeholder:"例）青山1-1-1"%>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">建物名</label>
          <span class="form-any">任意</span>
        </div>
        <%= f.text_field :building_name, class:"input-default", id:"building", placeholder:"例）柳ビル103"%>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">電話番号</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :phone_number, class:"input-default", id:"phone-number", placeholder:"例）09012345678",maxlength:"11"%>
      </div>
    </div>
    <%# お客様情報入力 %>
    
    <%# カード情報の入力 %>
    <div class='credit-card-form'>
      <h1 class='info-input-haedline'>
        クレジットカード情報入力
      </h1>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">カード情報</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :number, class:"input-default", id:"card-number", placeholder:"カード番号(半角英数字)", maxlength:"16" %>
        <div class='available-card'>
          <%= image_tag 'card-visa.gif', class: 'card-logo'%>
          <%= image_tag 'card-mastercard.gif', class: 'card-logo'%>
          <%= image_tag 'card-jcb.gif', class: 'card-logo'%>
          <%= image_tag 'card-amex.gif', class: 'card-logo'%>
        </div>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">有効期限</label>
          <span class="indispensable">必須</span>
        </div>
        <div class='input-expiration-date-wrap'>
          <%= f.text_area :exp_month, class:"input-expiration-date", id:"card-exp-month", placeholder:"例)3" %>
          <p>月</p>
          <%= f.text_area :exp_year, class:"input-expiration-date", id:"card-exp-year", placeholder:"例)23" %>
          <p>年</p>
        </div>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">セキュリティコード</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :cvc, class:"input-default", id:"card-cvc", placeholder:"カード背面4桁もしくは3桁の番号", maxlength:"4" %>
      </div>
    </div>
    <%# /カード情報の入力 %>
    <div class='buy-btn'>
      <%= f.submit "購入" ,class:"buy-red-btn", id:"button" %>
    </div>
    <% end %>
  </div>
</div>