config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#index'
  resources :users,  only: :index
  resources :orders, only: [:index, :new, :create]
  resources :homes,  only: :index do
    collection do
      get 'tushima'
      get 'iki'
      get 'access'
    end
  end
  resources :foods,  only: [:new, :create, :edit, :update, :destroy, :index] do
    collection do
      get 'search'
    end
  end
  resources :hotels, only: [:new, :create, :edit, :update, :destroy, :index] do
    collection do
      get 'search'
    end
  end
end

app/models/food.rb
class Food < ApplicationRecord
  has_one_attached :image
  belongs_to :user

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :genre
  belongs_to :island
  belongs_to :opening_hour

  with_options presence: true do
    validates :image, :store_name, :address, :tagline, :details
  end
  with_options numericality: { other_than: 1, message: 'を選択してください' } do
    validates :island_id, :genre_id, :opening_hour_id
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_q, only: [:index, :search]

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    if @food.save
      redirect_to controller: :users, action: :index
    else
      render :new
    end
  end

  def edit
    @food = Food.find(params[:id])
  end

  def update
    food = Food.find(params[:id])
    food.update(food_params)
    redirect_to controller: :users, action: :index
  end

  def destroy
    food = Food.find(params[:id])
    food.destroy
  end

  def index
    @foods = Food.all
  end

  def search
    @results = @q.result
  end

  private

  def food_params
    params.require(:food).permit(:store_name, :address, :tagline, :google_url, :details, :genre_id, :island_id, :opening_hour_id,
                                 :image).merge(user_id: current_user.id)
  end

  def set_q
    @q = Food.ransack(params[:q])
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/destroy.html.erb
<div class="success-back">
  <div class="success">
    <h3>削除が完了しました。</h3>
    <%= link_to "ユーザートップへ戻る", users_path %>
  </div>
</div>

app/views/foods/edit.html.erb
<div class="contents-row">
  <div class="container">
    <div class="title">
      <p>飲食店情報の編集</p>
    </div>
    <div class="form"> 
      <%= form_with model: @food, local: true do |f| %>
      <%= render 'shared/error_messages', model: @food %>
      <div class="field">
        <div class="img-upload">
          <div class="weight-bold-text">
            商品画像
          </div>
          <div class="click-upload">
            <p>
              クリックしてファイルをアップロード
            </p>
            <%= f.file_field :image, id:"food-image" %>
          </div>
        </div>
      </div>
      <div class="field">
        <div id="image-list"></div>
      </div>
      <div class="field">
        <%= f.label :store_name %><br />
        <%= f.text_area :store_name, autofocus: true %>
      </div>
      <div class="field">
        <%= f.label :address %><br />
        <%= f.text_area :address, autofocus: true %>
      </div>
      <div class="field">
        <%= f.label :tagline %><br />
        <%= f.text_area :tagline,  placeholder:"キャッチコピーお願いします！" %>
      </div>
      <div class="field">
        <%= f.label :google_url %><br />
        <%= f.text_area :google_url, placeholder:"GoogleマップからのURL貼り付け" %>
      </div>
      <div class="field">
        <%= f.label :details %><br />
        <%= f.text_area :details, placeholder:"店舗紹介文 or URL" %>
      </div>
      <div class="field">お住まいの島,ジャンル,営業時間帯
          <%= f.collection_select(:island_id, Island.all, :id, :name, {}, {class:"select-box", id:"island"}) %>
          <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"select-box", id:"food-genre"}) %>
          <%= f.collection_select(:opening_hour_id, OpeningHour.all, :id, :name, {}, {class:"select-box", id:"opening-hour"}) %>
      </div>
      <div class="actions">
        <input type="submit" name="commit" value="登録" data-disable-with="Register">
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/foods/index.html.erb
<div class="vcontents-row">
  <p class="eatlogo">島を食べる</p>
  <p class="eat-image">
    <span><%= image_tag 'eat_image.jpeg', class: "image1" %></span>
    <span><%= image_tag 'eat_image2.jpeg', class: "image2" %></span>
  </p>
  <div class="search">
    <div class="search-inner">
      <%= search_form_for @q, url: search_foods_path do |f| %>
        <%= f.label :island_id_eq, 'エリア' %>
        <%= f.collection_select :island_id_eq, Island.where.not(id: 1), :id, :name,  include_blank: '指定なし' %>
        <%= f.label :genre_id_eq, 'ジャンル' %>
        <%= f.collection_select :genre_id_eq, Genre.where.not(id: 1), :id, :name,  include_blank: '指定なし' %>
        <%= f.label :opening_hour_id_eq, '営業時間' %>
        <%= f.collection_select :opening_hour_id_eq, OpeningHour.where.not(id: 1), :id, :name,  include_blank: '指定なし' %>
        <br>
        <%= f.submit '検索' %>
      <% end %>
    </div>
  </div>
  <div class="v-data">
    <% unless @foods.present? %>
      <div class="results-zero">情報が更新されますのをお待ちください</div>
    <% else %>
      <div class="results-num"><%=@foods.count%>件ヒットしました</div>
    <% end %>
    <ul class="vfood-data">
      <% @foods.each do |food| %>
        <li class='vlist'>
          <div class="vphoto-grid">
            <p><%= image_tag food.image, class: "vimg" %><p>
            <ul>
              <li><strong>島:</strong><%=food.island.name%></li>
              <li><strong>ジャンル:</strong><%=food.genre.name%></li>
              <li><strong>営業時間:</strong><%=food.opening_hour.name%></li>
            </ul>
          </div>
          <div class="vinfo-grid">
            <ul class="vinfo-field">
              <li class="tagline"><%= food.tagline %></li>
              <li><b><%= food.store_name %></b></li>
              <li class="row2"><strong>住所:</strong><%= food.address %></li>
              <li class="row3"><strong>詳細:</strong><%= food.details %></li>
              <li class="row4"><strong>Google URL:</strong><%= food.google_url %></li>
            </ul>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/foods/new.html.erb
<div class="contents-row">
  <div class="container">
    <div class="title">
      <p>あなたの町の飲食店を登録</p>
    </div>
    <div class="form"> 
      <%= form_with model: @food, local: true do |f| %>
      <%= render 'shared/error_messages', model: @food %>
      <div class="field">
        <div class="img-upload">
          <div class="weight-bold-text">
            商品画像
          </div>
          <div class="click-upload">
            <p>
              クリックしてファイルをアップロード
            </p>
            <%= f.file_field :image, id:"food-image" %>
          </div>
        </div>
      </div>
      <div class="field">
        <div id="image-list"></div>
      </div>
      <div class="field">
        <%= f.label :store_name %><br />
        <%= f.text_area :store_name, autofocus: true %>
      </div>
      <div class="field">
        <%= f.label :address %><br />
        <%= f.text_area :address, autofocus: true %>
      </div>
      <div class="field">
        <%= f.label :tagline %><br />
        <%= f.text_area :tagline,  placeholder:"キャッチコピーお願いします！" %>
      </div>
      <div class="field">
        <%= f.label :google_url %><br />
        <%= f.text_area :google_url, placeholder:"GoogleマップからのURL  空でもOK" %>
      </div>
      <div class="field">
        <%= f.label :details %><br />
        <%= f.text_area :details, placeholder:"店舗紹介文 or URL" %>
      </div>
      <div class="field">お住まいの島,ジャンル,営業時間帯
          <%= f.collection_select(:island_id, Island.all, :id, :name, {}, {class:"select-box", id:"island"}) %>
          <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"select-box", id:"food-genre"}) %>
          <%= f.collection_select(:opening_hour_id, OpeningHour.all, :id, :name, {}, {class:"select-box", id:"opening-hour"}) %>
      </div>
      <div class="actions">
        <input type="submit" name="commit" value="登録" data-disable-with="Register">
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/foods/search.html.erb
<div class="vcontents-row">
  <p class="eatlogo">島を食べる</p>
  <p class="eat-image">
    <span><%= image_tag 'eat_image.jpeg', class: "image1" %></span>
    <span><%= image_tag 'eat_image2.jpeg', class: "image2" %></span>
  </p>
  <div class="search">
    <div class="search-inner">
      <%= search_form_for @q, url: search_foods_path do |f| %>
        <%= f.label :island_id_eq, 'エリア' %>
        <%= f.collection_select :island_id_eq, Island.where.not(id: 1), :id, :name,  include_blank: '指定なし' %>
        <%= f.label :genre_id_eq, 'ジャンル' %>
        <%= f.collection_select :genre_id_eq, Genre.where.not(id: 1), :id, :name,  include_blank: '指定なし' %>
        <%= f.label :opening_hour_id_eq, '営業時間' %>
        <%= f.collection_select :opening_hour_id_eq, OpeningHour.where.not(id: 1), :id, :name,  include_blank: '指定なし' %>
        <br>
        <%= f.submit '検索' %>
      <% end %>
     </div> 
  </div>
  <div class="v-data">
    <% unless @results.present? %>
      <div class="results-zero">検索ヒットしませんでした</div>
    <% else %>
    <div class="results-num"><%=@results.count%>件ヒットしました</div>
    <% end %>
    <ul class="vfood-data">
      <% @results.each do |food| %>
      <li class='vlist'>
        <div class="vphoto-grid">
            <p><%= image_tag food.image, class: "vimg" %><p>
            <ul>
              <li><strong>島:</strong><%=food.island.name%></li>
              <li><strong>ジャンル:</strong><%=food.genre.name%></li>
              <li><strong>営業時間:</strong><%=food.opening_hour.name%></li>
            </ul>
          </div>
          <div class="vinfo-grid">
            <ul class="vinfo-field">
              <li class="tagline"><%= food.tagline %></li>
              <li><b><%= food.store_name %></b></li>
              <li class="row2"><strong>住所:</strong><%= food.address %></li>
              <li class="row3"><strong>詳細:</strong><%= food.details %></li>
              <li class="row4"><strong>Google URL:</strong><%= food.google_url %></li>
            </ul>
          </div>
      </li>
      <%end%>
    </ul>
  </div>
</div>