config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#index'
  resources :users,  only: :index
  resources :orders, only: [:index, :new, :create]
  resources :homes,  only: :index do
    collection do
      get 'tushima'
      get 'iki'
      get 'access'
    end
  end
  resources :foods,  only: [:new, :create, :edit, :update, :destroy, :index] do
    collection do
      get 'search'
    end
  end
  resources :hotels, only: [:new, :create, :edit, :update, :destroy, :index] do
    collection do
      get 'search'
    end
  end
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  has_one_attached :image
  belongs_to :user

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :island
  belongs_to :location
  belongs_to :price_range

  with_options presence: true do
    validates :image, :hotel_name, :address, :tagline, :details
  end
  with_options numericality: { other_than: 1, message: 'を選択してください' } do
    validates :island_id, :location_id, :price_range_id
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_q, only: [:index, :search]

  def new
    @hotel = Hotel.new
  end

  def create
    @hotel = Hotel.new(hotel_params)
    if @hotel.save
      redirect_to controller: :users, action: :index
    else
      render :new
    end
  end

  def edit
    @hotel = Hotel.find(params[:id])
  end

  def update
    hotel = Hotel.find(params[:id])
    hotel.update(hotel_params)
    redirect_to controller: :users, action: :index
  end

  def destroy
    hotel = Hotel.find(params[:id])
    hotel.destroy
  end

  def index
    @hotels = Hotel.all
  end

  def search
    @results = @q.result
  end

  private

  def hotel_params
    params.require(:hotel).permit(:hotel_name, :address, :tagline, :google_url, :details, :location_id, :island_id,
                                  :price_range_id, :image).merge(user_id: current_user.id)
  end

  def set_q
    @q = Hotel.ransack(params[:q])
  end
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/hotels/destroy.html.erb
<div class="success-back">
  <div class="success">
    <h3>削除が完了しました。</h3>
    <%= link_to "ユーザートップへ戻る", users_path %>
  </div>
</div>

app/views/hotels/edit.html.erb
<div class="contents-row">
  <div class="container">
    <div class="title">
      <p>ホテル・宿情報の編集</p>
    </div>
    <div class="form"> 
      <%= form_with model: @hotel, local: true do |f| %>
      <%= render 'shared/error_messages', model: @hotel %>
      <div class="field">
       
        <div class="img-upload">
          <div class="weight-bold-text">
            商品画像
          </div>
          <div class="click-upload">
            <p>
              クリックしてファイルをアップロード
            </p>
            <%= f.file_field :image, id:"hotel-image" %>
          </div>
        </div>
      </div>
      <div class="field">
        <div id="image-list"></div>
      </div>
      <div class="field">
        <%= f.label :hotel_name %><br />
        <%= f.text_area :hotel_name, autofocus: true %>
      </div>
      <div class="field">
        <%= f.label :address %><br />
        <%= f.text_area :address, autofocus: true %>
      </div>
      <div class="field">
        <%= f.label :tagline %><br />
        <%= f.text_area :tagline,  placeholder:"キャッチコピーお願いします！" %>
      </div>
      <div class="field">
        <%= f.label :google_url %><br />
        <%= f.text_area :google_url, placeholder:"GoogleマップからのURL貼り付け" %>
      </div>
      <div class="field">
        <%= f.label :details %><br />
        <%= f.text_area :details, placeholder:"店舗紹介文 or URL" %>
      </div>
      <div class="field">所在地,エリア,価格帯
          <%= f.collection_select(:island_id, Island.all, :id, :name, {}, {class:"select-box", id:"island"}) %>
          <%= f.collection_select(:location_id, Location.all, :id, :name, {}, {class:"select-box", id:"hotel-location"}) %>
          <%= f.collection_select(:price_range_id, PriceRange.all, :id, :name, {}, {class:"select-box", id:"price-range"}) %>
      </div>
      <div class="actions">
        <input type="submit" name="commit" value="登録" data-disable-with="Register">
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/hotels/index.html.erb
<div class="vcontents-row">
  <p class="eatlogo">島に泊まる</p>
  <p class="eat-image">
    <span><%= image_tag 'hotel_image3.jpeg', class: "image1" %></span>
    <span><%= image_tag 'hotel_image4.jpeg', class: "image2" %></span>
  </p>
  <div class="search">
    <div class="search-inner">
      <%= search_form_for @q, url: search_hotels_path do |f| %>
        <%= f.label :island_id_eq, 'エリア' %>
        <%= f.collection_select :island_id_eq, Island.where.not(id: 1), :id, :name,  include_blank: '指定なし' %>
        <%= f.label :location_id_eq, '所在地' %>
        <%= f.collection_select :location_id_eq, Location.where.not(id: 1), :id, :name,  include_blank: '指定なし' %>
        <%= f.label :price_range_id_eq, '価格帯' %>
        <%= f.collection_select :price_range_id_eq, PriceRange.where.not(id: 1), :id, :name,  include_blank: '指定なし' %>
        <br>
        <%= f.submit '検索' %>
      <% end %>
    </div>
  </div>
  <div class="v-data">
    <% unless @hotels.present? %>
      <div class="results-zero">情報が更新されますのをお待ちください</div>
    <% else %>
      <div class="results-num"><%=@hotels.count%>件ヒットしました</div>
    <% end %>
    <ul class="vfood-data">
      <% @hotels.each do |hotel| %>
        <li class='vlist'>
          <div class="vphoto-grid">
            <p><%= image_tag hotel.image, class: "vimg" %><p>
            <ul>
              <li><strong>エリア:</strong><%= hotel.island.name%></li>
              <li><strong>所在地:</strong><%= hotel.location.name%></li>
              <li><strong>価格帯:</strong><%= hotel.price_range.name%></li>
            </ul>
          </div>
          <div class="vinfo-grid">
            <ul class="vinfo-field">
              <li class="tagline"><%= hotel.tagline %></li>
              <li><b><%= hotel.hotel_name %></b></li>
              <li class="row2"><strong>住所:</strong><%= hotel.address %></li>
              <li class="row3"><strong>詳細:</strong><%= hotel.details %></li>
              <li class="row4"><strong>Google URL:</strong><%= hotel.google_url %></li>
            </ul>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/hotels/new.html.erb
<div class="contents-row">
  <div class="container">
    <div class="title">
      <p>あなたの町のホテル・宿</p>
    </div>
    <div class="form"> 
      <%= form_with model: @hotel, local: true do |f| %>
      <%= render 'shared/error_messages', model: @hotel %>
      <div class="field">
        <div class="img-upload">
          <div class="weight-bold-text">
            商品画像
          </div>
          <div class="click-upload">
            <p>
              クリックしてファイルをアップロード
            </p>
            <%= f.file_field :image, id:"hotel-image" %>
          </div>
        </div>
      </div>
      <div class="field">
        <div id="image-list"></div>
      </div>
      <div class="field">
        <%= f.label :hotel_name %><br />
        <%= f.text_area :hotel_name, autofocus: true %>
      </div>
      <div class="field">
        <%= f.label :address %><br />
        <%= f.text_area :address, autofocus: true %>
      </div>
      <div class="field">
        <%= f.label :tagline %><br />
        <%= f.text_area :tagline,  placeholder:"キャッチコピーお願いします！" %>
      </div>
      <div class="field">
        <%= f.label :google_url %><br />
        <%= f.text_area :google_url, placeholder:"GoogleマップからのURL  空でもOK" %>
      </div>
      <div class="field">
        <%= f.label :details %><br />
        <%= f.text_area :details, placeholder:"店舗紹介文 or URL" %>
      </div>
      <div class="field">所在地,エリア,価格帯
          <%= f.collection_select(:island_id, Island.all, :id, :name, {}, {class:"select-box", id:"island"}) %>
          <%= f.collection_select(:location_id, Location.all, :id, :name, {}, {class:"select-box", id:"hotel-location"}) %>
          <%= f.collection_select(:price_range_id, PriceRange.all, :id, :name, {}, {class:"select-box", id:"price-range"}) %>
      </div>
      <div class="actions">
        <input type="submit" name="commit" value="登録" data-disable-with="Register">
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/hotels/search.html.erb
<div class="vcontents-row">
  <p class="eatlogo">島に泊まる</p>
  <p class="eat-image">
    <span><%= image_tag 'hotel_image3.jpeg', class: "image1" %></span>
    <span><%= image_tag 'hotel_image4.jpeg', class: "image2" %></span>
  </p>
  <div class="search">
    <div class="search-inner">
      <%= search_form_for @q, url: search_hotels_path do |f| %>
        <%= f.label :island_id_eq, 'エリア' %>
        <%= f.collection_select :island_id_eq, Island.where.not(id: 1), :id, :name,  include_blank: '指定なし' %>
        <%= f.label :location_id_eq, '所在地' %>
        <%= f.collection_select :location_id_eq, Location.where.not(id: 1), :id, :name,  include_blank: '指定なし' %>
        <%= f.label :price_range_id_eq, '価格帯' %>
        <%= f.collection_select :price_range_id_eq, PriceRange.where.not(id: 1), :id, :name,  include_blank: '指定なし' %>
        <br>
        <%= f.submit '検索' %>
      <% end %>
    </div>
  </div>
  <div class="v-data">
    <% unless @results.present? %>
      <div class="results-zero">検索ヒットしませんでした</div>
    <% else %>
    <div class="results-num"><%=@results.count%>件ヒットしました</div>
    <% end %>
    <ul class="vfood-data">
      <% @results.each do |hotel| %>
      <li class='vlist'>
        <div class="vphoto-grid">
          <p><%= image_tag hotel.image, class: "vimg" %><p>
          <ul>
            <li><strong>エリア:</strong><%= hotel.island.name%></li>
            <li><strong>所在地:</strong><%= hotel.location.name%></li>
            <li><strong>価格帯:</strong><%= hotel.price_range.name%></li>
          </ul>
        </div>
        <div class="vinfo-grid">
          <ul class="vinfo-field">
            <li class="tagline"><%= hotel.tagline %></li>
            <li><b><%= hotel.hotel_name %></b></li>
            <li class="row2"><strong>住所:</strong><%= hotel.address %></li>
            <li class="row3"><strong>詳細:</strong><%= hotel.details %></li>
            <li class="row4"><strong>Google URL:</strong><%= hotel.google_url %></li>
          </ul>
          </div>
      </li>
      <%end%>
    </ul>
  </div>
</div>